SOURCE_SECRET = "SAES4O3NXUE2CPIB7YH3O5ROAONADPZRXOEYFC4JPLNY6STOBM2RYLGH"
ADMIN_SECRET = "SDFWYGBNP5TW4MS7RY5D4FILT65R2IEPWGL34NY2TLSU4DC4BJNXUAMU"
ORACLE_CONTRACT_ID = "CBJKOC77D3DQHBXENUQL5FM56DE2WRRVRZ4B4FPWRQUFB5FZ74TJ6STH"
PRICEUPDOWN_CONTRACT_ID = "CDIBCMVBGATZQEMYH5ORERHKRUCAQRESFMBQV3FJRDJPVGJNJMYMLWNQ"  # contract id of the deployed PriceUpDown contract
STELLAR_NETWORK="testnet"  # testnet, futurenet or public
